services:
  db:
    image: postgres:17.2-alpine3.20
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: maiordomus-be
      POSTGRES_USER: maiordomus
      POSTGRES_DB: maiordomus
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  data: